#!/bin/bash

# @asuweb

if ps -C php -o args h | grep mailwatch_postfix_relay.php
then true ## mailwatch_postfix_relay.php running
else /usr/bin/php -q /usr/local/bin/mailwatch_postfix_relay.php > /dev/null &
fi
if ps -C php -o args h | grep mailwatch_milter_relay.php
then true ## mailwatch_milter_relay.php running
else /usr/bin/php -q /usr/local/bin/mailwatch_milter_relay.php > /dev/null &
fi

